# Generated by Django 3.1.1 on 2020-10-05 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='image')),
                ('mealTime', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('totalCal', models.IntegerField(null=True)),
                ('foods', models.ManyToManyField(blank=True, related_name='foods', to='food.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
