# Generated by Django 3.1.1 on 2020-10-07 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='foods',
        ),
        migrations.AddField(
            model_name='menu',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.food'),
        ),
    ]
