# Generated by Django 3.1.1 on 2020-10-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM', models.IntegerField(null=True)),
                ('FOOD_CD', models.CharField(max_length=20)),
                ('SAMPLING_REGION_NAME', models.CharField(max_length=20, null=True)),
                ('SAMPLING_MONTH_NAME', models.CharField(max_length=2, null=True)),
                ('SAMPLING_REGION_CD', models.CharField(max_length=20, null=True)),
                ('SAMPLING_MONTH_CD', models.CharField(max_length=20, null=True)),
                ('GROUP_NAME', models.CharField(max_length=20, null=True)),
                ('DESC_KOR', models.CharField(max_length=50, null=True)),
                ('RESEARCH_YEAR', models.CharField(max_length=4, null=True)),
                ('MAKER_NAME', models.CharField(max_length=50, null=True)),
                ('SUB_REF_NAME', models.CharField(max_length=50, null=True)),
                ('SERVING_SIZE', models.TextField(null=True)),
                ('NUTR_CONT1', models.TextField(null=True)),
                ('NUTR_CONT2', models.TextField(null=True)),
                ('NUTR_CONT3', models.TextField(null=True)),
                ('NUTR_CONT4', models.TextField(null=True)),
                ('NUTR_CONT5', models.TextField(null=True)),
                ('NUTR_CONT6', models.TextField(null=True)),
                ('NUTR_CONT7', models.TextField(null=True)),
                ('NUTR_CONT8', models.TextField(null=True)),
                ('NUTR_CONT9', models.TextField(null=True)),
                ('ANIMAL_PLANT', models.CharField(max_length=50, null=True)),
                ('BGN_YEAR', models.CharField(max_length=50, null=True)),
                ('FOOD_GROUP', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
